spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: secret
    username: myuser
    url: jdbc:postgresql://localhost/mydatabase
  application:
    name: orders-service

generate:
  endpoint: http://213.171.28.72:8080/numbers/generate

logging:
  level:
    sql: debug
